project_id = "drrsbklxmktszxcqahdg"

[functions.geocode-address]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.get-subscription-status]
verify_jwt = true

[functions.auto-complete-bookings]
verify_jwt = false

